import React from 'react'
import Link from 'next/link'
import { Card } from '@/components/ui/Card'
import { FileText, Calendar, ArrowRight, User } from 'lucide-react'

export interface ReportItem {
  id: string
  title: string
  periodStart: string
  periodEnd: string
  createdAt: string
  generatedBy?: {
    name: string | null
    email: string
  } | null
  contentJson?: {
    stats?: {
      totalItems?: number
      percentNegative?: number
    }
  }
}

export function ReportCard({ report }: { report: ReportItem }) {
  const dtCreated = new Date(report.createdAt)
  const dtStart = new Date(report.periodStart)
  const dtEnd = new Date(report.periodEnd)

  const formattedPeriod = `${!isNaN(dtStart.getTime()) ? dtStart.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : report.periodStart} – ${!isNaN(dtEnd.getTime()) ? dtEnd.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }) : report.periodEnd}`
  const formattedCreated = !isNaN(dtCreated.getTime()) ? dtCreated.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : ''

  return (
    <Card className="p-5 hover:border-indigo-200 dark:hover:border-indigo-900/50 transition-all hover:shadow-md">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3.5">
          <div className="p-3 rounded-2xl bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h3 className="font-bold text-base text-zinc-900 dark:text-zinc-100">
              {report.title}
            </h3>
            <div className="flex items-center gap-2 mt-1 text-xs text-zinc-500">
              <Calendar className="w-3.5 h-3.5" />
              <span>{formattedPeriod}</span>
            </div>
          </div>
        </div>

        <Link
          href={`/reports/${report.id}`}
          className="p-2 rounded-xl bg-zinc-100 hover:bg-indigo-600 hover:text-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-300 transition-colors"
        >
          <ArrowRight className="w-4 h-4" />
        </Link>
      </div>

      <div className="mt-4 pt-4 border-t border-zinc-100 dark:border-zinc-800 flex items-center justify-between text-xs text-zinc-400">
        <div className="flex items-center gap-1.5">
          <User className="w-3.5 h-3.5" />
          <span>Generated by {report.generatedBy?.name || report.generatedBy?.email || 'Admin'}</span>
        </div>
        <span>{formattedCreated}</span>
      </div>
    </Card>
  )
}
